// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkDYpYKp2unAfKaVxD6GakHfJgDYDDOmo',
    appId: '1:778114657422:web:2d79544ab48947a82c6ddf',
    messagingSenderId: '778114657422',
    projectId: 'pharmflow-8cc91',
    authDomain: 'pharmflow-8cc91.firebaseapp.com',
    storageBucket: 'pharmflow-8cc91.firebasestorage.app',
    measurementId: 'G-NB2LYSDR29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaDTcs7Mlbh90NlD-vyiXtdRXY3ScHL0k',
    appId: '1:778114657422:android:f46e050fc72207cc2c6ddf',
    messagingSenderId: '778114657422',
    projectId: 'pharmflow-8cc91',
    storageBucket: 'pharmflow-8cc91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ7neADGP7q1i2AWFdWgwbWknlIhsB5nA',
    appId: '1:778114657422:ios:5824fd730741e1be2c6ddf',
    messagingSenderId: '778114657422',
    projectId: 'pharmflow-8cc91',
    storageBucket: 'pharmflow-8cc91.firebasestorage.app',
    iosBundleId: 'com.example.pharmacymanagement',
  );
}
